### ISSUE TITLE
documentation on how to add UPI node to running cluster (post-install)

### ISSUE THREAD

**Issue by ibotty** [openshift/okd#134]
I could not find any documentation to add another node (master/worker/custom mcp) to a running cluster, e.g. after initial installation.

Where can I find it?

**Comment by vrutkovs** [comment]
That sounds like a good suggestion for openshift-docs. 

In general you'd simply start a new machine and use `worker.ign` as an ignition source, same way its done during initial installation

**Comment by cgruver** [comment]
You might be able to pull what you need out of some docs that I've been writing for folks that I work with.  https://github.com/cgruver/okd4-upi-lab-setup

As long as you still have the worker ignition file in place, it's just a matter of booting a new worker with FCOS pointed at that file.

The tutorial I am working on, sets things up for iPXE boot.  That makes it CRAZY easy to add a worker.  __The docs will shortly be updated for folks who are using dhcpd and tftp on a linux OS rather than an OpenWRT router__. But, all of the pieces that you need are in there.

You will have to monitor the install and approve the CSR.  Otherwise it is pretty automatic.

`oc get csr` 

Watch for "Pending" CSRs, and approve them:

`oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs oc adm certificate approve`

**Comment by vrutkovs** [comment]
https://docs.okd.io/latest/machine_management/user_infra/adding-bare-metal-compute-user-infra.html
