### ISSUE TITLE
Fix bypass for pull-secret

### ISSUE THREAD

**Issue by sapkra** [openshift/okd#182]
Like it's described in the README a bypass is needed for the pull-secret. This should be fixed - if it is already the README should be changed.

I've added this issue because I think it is important for the stable release and it has to be documented so that no one will forget about it. The `(fix coming soon)` comment in the README was added in November last year.

**Comment by vrutkovs** [comment]
Unfortunately we'd have to ship GA with this workaround (`{"auths":{"fake":{"auth": "bar"}}}`) due to lack of time to prepare a fix which can be merged upstream

**Comment by vrutkovs** [comment]
https://github.com/openshift/okd/issues/264 has a better description of the same problem

**Comment by jkassis** [comment]
using this pull secret... `{"auths":{"fake":{"auth": "bar"}}}` i now have problems with my s2i build config.

`Cloning "git@github.com:jkassis/xxxxx.git" ...
	Commit:	f55bf64db1ce4366eb8319f8a507e6cc5f114216 (working on s2i build)
	Author:	Jeremy Kassis <jkassis@gmail.com>
	Date:	Mon Jul 27 17:53:51 2020 -0700
Caching blobs under "/var/cache/blobs".
E0728 04:28:56.827076       1 config.go:236] while trying to parse blob "{\"auths\":{\"fake\":{\"auth\":\"bar\"}}}\n": unable to parse auth field
Warning: Pull failed, retrying in 5s ...
E0728 04:29:02.732065       1 config.go:236] while trying to parse blob "{\"auths\":{\"fake\":{\"auth\":\"bar\"}}}\n": unable to parse auth field
Warning: Pull failed, retrying in 5s ...
E0728 04:29:08.762960       1 config.go:236] while trying to parse blob "{\"auths\":{\"fake\":{\"auth\":\"bar\"}}}\n": unable to parse auth field
Warning: Pull failed, retrying in 5s ...
error: build error: After retrying 2 times, Pull image still failed due to error: errors:
denied: requested access to the resource is denied
unauthorized: authentication required`

![image](https://user-images.githubusercontent.com/3630156/88619762-259a0280-d051-11ea-94a4-a25a01e59c8b.png)

**Comment by jkassis** [comment]
i changed the content of `-n openshift-config secret/pull-secret` but this error continues to raise. `oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=/Users/jkassis/.docker/config.json`

**Comment by jkassis** [comment]
changing the pull-secret actually *did* change this message. it just took a while to propagate.
