### ISSUE TITLE
OKD 4.5 Cluster showing 60 days trial!

### ISSUE THREAD

**Issue by SureshPatare** [openshift/okd#466]
I installed test cluster (OKD 4.5) on virtual machines and it is registered on my Redhat account https://cloud.redhat.com/openshift/ where it is showing a warning that I have 60 days trial period!

Now if the OKD is open source, wondering why this error? Will the cluster break after 60 days? I am using Fedora CoreOS for all nodes in my cluster and all the installation binaries are taken from Github. 

I even tried installing cluster without any account, however in that case I don't get option to upgrade the cluster.

**Comment by vrutkovs** [comment]
>Now if the OKD is open source

Both OKD and OCP are opensource.

> wondering why this error? 

Since cloud.redhat.com doesn't know if OCP or OKD would be installed using the received pull secret, it assigns default license to the cluster. There is no commercial support from Red Hat for OKD servers, so it doesn't apply to OKD installations

> Will the cluster break after 60 days? 

No. According to the license after 60 days you should either change the license or remove the installed Red Hat software. OKD is a community distribution, so it doesn't apply to OKD either.

> I even tried installing cluster without any account, however in that case I don't get option to upgrade the cluster.

That must be a bug (release controller has had a few outages last week). Upgrades are unrelated to the used pull secret and apply to any kind of cluster.

**Comment by SureshPatare** [comment]
I waited for 60 days to see whether the cluster really breaks; but it didn't! Thanks much Vadim for this incredible help!!!

**Comment by JayDoubleu** [comment]
@vrutkovs so I just installed the OKD cluster using the assistant and it show the trial.
Is there any way to disable this early so I'll be only installing stuff that will not expire ?
