### ISSUE TITLE
Trying to force  upgrade to 4.6.0-0.okd-2021-01-17-185703

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#468]
**Trying to force  upgrade to 4.6.0-0.okd-2021-01-17-185703**
oc adm upgrade --force --to=4.6.0-0.okd-2021-01-17-185703 --allow-upgrade-with-warnings

**Current Version**
4.5.0-0.okd-2020-10-15-235428

**Getting Error:**
error: The update 4.6.0-0.okd-2021-01-17-185703 is not one of the available updates: 4.6.0-0.okd-2020-11-27-200126, 4.6.0-0.okd-2020-12-12-135354

Please advise

**Comment by vrutkovs** [comment]
What's your current version?

**Comment by mafna** [comment]
I have the same issue.

My OKD version is "Cluster version is 4.5.0-0.okd-2020-10-15-235428".

Under 

 oc adm upgrade
Cluster version is 4.5.0-0.okd-2020-10-15-235428

"oc adm upgrade" shows only

VERSION                       IMAGE
4.6.0-0.okd-2020-11-27-200126 registry.ci.openshift.org/origin/release@sha256:a5392db432c990ee012ab189e9fa0d7b6a168f6e9b9e9da7fb10768b48752ca0
4.6.0-0.okd-2020-12-12-135354 registry.ci.openshift.org/origin/release@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c

**Comment by johnlongo** [comment]
Current Version
4.5.0-0.okd-2020-10-15-235428

**Comment by johnlongo** [comment]
> What's your current version?

Current Version
4.5.0-0.okd-2020-10-15-235428

**Comment by vrutkovs** [comment]
There is no edge between 4.5.0-0.okd-2020-10-15-235428 and 4.6.0-0.okd-2021-01-17-185703, see [Upgrades From](https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.6.0-0.okd-2021-01-17-185703)

Is there a reason you want to jump from 4.5 to this release directly, instead of incremental upgrades to previous releases?

**Comment by mafna** [comment]
We had an issues when upgrading from 4.5.0-0.okd-2020-10-15-235428 to 4.6.0-0.okd-2020-11-27-200126 or 4.6.0-0.okd-2020-12-12-135354. Every time the result is the same - #440 and #649. Can not get pass this. We have UPI (baremetal) installation of OKD.

**Comment by vrutkovs** [comment]
okay, adding edges from 4.5.0-0.okd-2020-10-15-235428 and 4.6.0-0.okd-2021-01-17-185703 there as well

**Comment by johnlongo** [comment]
When do you think I'll be able to force the upgrade from my 4.5.0-0.okd-2020-10-15-235428 cluster.
I tried it yesterday and it still didn't accept the force.

**Comment by mervincm** [comment]
> When do you think I'll be able to force the upgrade from my 4.5.0-0.okd-2020-10-15-235428 cluster.
> I tried it yesterday and it still didn't accept the force.
> 
> Just tried it gain same issue.
> 
> oc adm upgrade --force --to=4.6.0-0.okd-2021-01-17-185703 --allow-upgrade-with-warnings
> 
> error: The update 4.6.0-0.okd-2021-01-17-185703 is not one of the available updates: 4.6.0-0.okd-2020-12-12-135354, 4.6.0-0.okd-2020-11-27-200126

you are not alone. I have a okd 4.5.0-0.okd-2020-10-15-235428 cluster as well. mine is essentially physical hardware but in vms on vmware based on Craig robinson's blog post. I fail upgrade attempts to either of the 4.6's released in 2020, yet those are the only ones oc adm upgrade offers as options.

I just tried it via command line forced to current.

oc adm upgrade --force --to=4.6.0-0.okd-2021-01-17-185703 --allow-upgrade-with-warnings

and got the same error message

error: The update 4.6.0-0.okd-2021-01-17-185703 is not one of the available updates: 4.6.0-0.okd-2020-12-12-135354, 4.6.0-0.okd-2020-11-27-200126

**Comment by mafna** [comment]
I tried with command "oc adm upgrade --to-image quay.io/openshift/okd@sha256:121b58e61104277260caf82ac09577a6321d047849f9caac632d1338aa6018a1 --allow-explicit-upgrade" and it started upgrading with warning

warning: The requested upgrade image is not one of the available updates.  You have used --allow-explicit-upgrade to the update to proceed anyway
Updating to release image quay.io/openshift/okd@sha256:121b58e61104277260caf82ac09577a6321d047849f9caac632d1338aa6018a1

For image i used the link "pull from" - https://github.com/openshift/okd/releases.

But the upgrade/update was not successful. I do not know what i'm doing wrong because i not a single update/upgrade from version 4.5.0-0.okd-2020-10-15-235428 to any of 4.6.0 versions is not working or had failed. I'm starting to think that OKD is really just for fresh installs and maybe for some POCs and then you  delete it :(...

**Comment by vrutkovs** [comment]
#471 is preventing us from adding this edge. Please follow the updates in that ticket
