### ISSUE TITLE
Page not found following "Learn more about OpenShift update channels"

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift/okd#503]
**Describe the bug**
Looking for changing the upgrade channel, the dialog shows a linkg "Learn more about OpenShift update channels".
A first issue is that it should be labeled "Learn more about OKD update channels" but not critical.
The critical issue is that it points to a documentation page which doesn't exist: https://docs.okd.io/latest/04.html#understanding-upgrade-channels_updating-cluster-between-minor 

**Version**
4.6.0-0.okd-2021-01-23-132511

**How reproducible**
100%

**Log bundle**
No logs needed.

**Comment by vrutkovs** [comment]
Right, OKD doesn't use `eus-4.x` / `stable-4.x` / `fast` / `candidate` channels.
The only real channel we've got is `4-stable`, nightlies should use `oc adm upgrage --force` for updates.

I think we should be hiding the references to this page for now, until we come up a with a good description of OKD channels.

/assign @mburke5678

**Comment by mburke5678** [comment]
@sandrobonazzola The _Learn more about OpenShift update channels_ link is in the web console, correct?
@vrutkovs Who can fix the broken link from the console?

**Comment by vrutkovs** [comment]
That would be a bug for UI/Console team

**Comment by sandrobonazzola** [comment]
> @sandrobonazzola The _Learn more about OpenShift update channels_ link is in the web console, correct?
> @vrutkovs Who can fix the broken link from the console?

yes, it's on the web console

**Comment by mburke5678** [comment]
Created BZs:
4.5 https://bugzilla.redhat.com/show_bug.cgi?id=1927992
4.6 https://bugzilla.redhat.com/show_bug.cgi?id=1927993

@vrutkovs It looks like a bad URL in the links?? 
Does this look familiar? http://docs.okd.io/latest/04.html#understanding-upgrade-channels_updating-cluster-between-minor

**Comment by mburke5678** [comment]
@vrutkovs I edited the update pages to remove information about the update channels other than *stable-*, which is in the OKD web console. The upgrade procedures work and match what is in the product, both CLI and web console. I'm not sure we want to document the `--force` option for upgrading to avoid issues with unsupported upgrades (?)

I should think it an easier change for the console folks to update the link URL rather than remove the link. WDYT?
Internal-only preview
http://file.rdu.redhat.com/~mburke/okd-issue-503/updating/updating-cluster-between-minor.html#understanding-upgrade-channels_updating-cluster-between-minor

**Comment by mburke5678** [comment]
Dev BZ to fix console link: https://github.com/openshift/origin-branding/pull/11

**Comment by vrutkovs** [comment]
Fixed in latest 4.6/4.7
