### ISSUE TITLE
Page with list of Open Source Software and its versions would be great

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#8]
Hi,

I'm wondering which version of Elasticsearch is used in OKD. 

It would be great if there would be a list of the most important Open Source packages used in OKD (Istio, Elasticsearch, Grafana, ...).

Best regards,

Josef

**Comment by Reamer** [comment]
With the following command you get the sha256 of the okd-preview image.
`oc adm release info quay.io/openshift/okd@sha256:5d2e42d555d24bb1a60d20eb03ae7e288f4347cad6a68c5428d00598c5816678`
Because sha256 values are almost meaningless, you can get information about git commits with
`oc adm release info quay.io/openshift/okd@sha256:5d2e42d555d24bb1a60d20eb03ae7e288f4347cad6a68c5428d00598c5816678 --commit-urls`

**Comment by LorbusChris** [comment]
and BTW, neither Istio, Elasticsearch nor Grafana are part of OKD. They can be installed on top however.
