### ISSUE TITLE
openshift-install-linux-4.8.0-0.okd-2021-09-24-060535 missing baremetal platform

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift/okd#894]
**Describe the bug**

Trying to deploy OKD 4.8.0 on bare metal
```
# openshift-install  create  install-config 
? Platform  [Use arrows to move, type to filter, ? for more help]
> aws
  azure
  gcp
  openstack
  ovirt
  vsphere
```

**Version**
```
# openshift-install version
openshift-install 4.8.0-0.okd-2021-09-24-060535
built from commit 225720cc2adce8c2ee18aea45d474f442cbe0f78
release image registry.ci.openshift.org/origin/release@sha256:5c7eed455d5bf4b4c701903ed7135d73de942eccaf4007664ed62ccf5f36fa18
```

**Comment by vrutkovs** [comment]
We need at least #197 and then we can proceed with using `registry.ci.openshift.org/origin/4.9:baremetal-installer` as main installer

**Comment by radioactive73** [comment]
@sandrobonazzola For bare metal deploys you need to create an install-config.yaml file manually and specify the install dir where it exists. This might also work if you have the file in the same dir as the binary, also keep a copy of the yaml file because the installer consumes it.

Required config options: https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-configuration-parameters-required_installing-bare-metal

Ex (if install-config.yaml is in the 'install' dir):
openshift-install create install-config --dir=install/

Example yaml:
https://docs.openshift.com/container-platform/4.8/installing/installing_bare_metal/installing-bare-metal.html#installation-bare-metal-config-yaml_installing-bare-metal
