### ISSUE TITLE
After successfully upgrading from 4.7.0 to 4.8.0, I see three warning messages in the console

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#907]
After successfully upgrading from 4.7.0 to 4.8.0, I see three warning messages in the console (see below).
What do I need to do to get rid of them?

Oct 3, 2021, 3:39 PM
One or more cluster operators have been blocking minor version cluster upgrades for at least an hour for reason AdminAckRequired.  For more information refer to https://console-openshift-console.apps.xxxxxxxx.xxxx.xxx/settings/cluster/.
View details

Oct 3, 2021, 3:39 PM
Deprecated API that will be removed in the next EUS version is being used. Removing the workload that is using the extensions.v1beta1/ingresses API might be necessary for a successful upgrade to the next EUS cluster version. Refer to the apirequestcount.apiserver.openshift.io resources to identify the workload.
View details

Oct 3, 2021, 3:39 PM
Deprecated API that will be removed in the next version is being used. Removing the workload that is using the extensions.v1beta1/ingresses API might be necessary for a successful upgrade to the next cluster version. Refer to the apirequestcount.apiserver.openshift.io resources to identify the workload.

**Comment by titou10titou10** [comment]
Same for me
Explanations here: https://docs.okd.io/latest/updating/updating-cluster-prepare.html
I'm quite confused with the upgrade from 4.7 to 4.8...
OCP v4.8 is based on K8S v1.21, so I guess OKD should also be based on the same version, but the nodes have been upgraded to K8S v1.22.1 !
It seem the upgrade bring a mix of OCP/OKD v4.8 and v4.9 and so K8s v1.21/1.22
Also the OKD documentation contains info on v4.9 (see the link mentioned above).. but  where v4.8 is out since 3 days...
Maybe I should open a specific ticket for this
Other minor observations,  the descheduler operator is no more available in the RH catalog and there in o more a drop-down list to choose the "update channel" as before, it has to be typed by hand. Q: where do I find the list of valid channeles for OKD?
